### PR TITLE
Cleanup master branch

### PR DESCRIPTION
**Pull request by johnsmithdoe970**
This should only be the landing page, and shouldn't contain code.

Related: #1

### CODE REVIEW

**Comment by johnsmithdoe970** [comment]
There is a diff between master branch and 75x branch, not sure if we should backport current master branch changes into 75x.

**Comment by johnsmithdoe970** [comment]
Do not merge until gh-pages reconfig is done, of course. Feel free to close if you prefer keeping the existing method.

**Comment by sleirsgoevy** [comment]
The idea is that when future firmwares become available, they will be added as submodules too, and thus every firmware would be served from the same GH pages repository. Unfortunately it does not natively support serving content from multiple branches.

**Comment by johnsmithdoe970** [comment]
Ok that makes sense.

I guess what triggers my OCD is that I see one code in one repo, and one code is in a branch, so I don't know if you want to have multiple repos as firmware source, or if you want to have multiple branches inside a single repo (but maybe keep a "legacy" repo).

I was just happy to help cleaning things up if you need to.

Side note: Submodules are great for contributing back content to the source, but here I have the feeling that subtrees would be easier to manage, did you think of using those? Just my 2 cents.

**Pull request closed without merging**
